# File params
rpdr_src_dir:           "/pc/resta/RPDR_projects/RPDR/"
data_dir:               "data/06-30-2020/"
biobank_file_name:      "data/06-30-2020/BiobankPortal_mns43_2020-09-08-235244.csv"
plasma_file_name:       "data/06-30-2020/Asthma_Plasma_BBIds.xlsx"
output_file_header:     "data/06-30-2020/RPDR_cleaned_data_ACTH_adrenal_"
rpdr_file_header:       "data/06-30-2020/mns43_063020114847776198_"
rpdr_file_ending:       ".txt"
general_file_ending:    ".csv"
summary_stats_dir:      "data/06-30-2020/Summary_Stats/"
genotype_file_name:     "/proj/regeps/regep00/studies/PartnersBiobank/data/imputed/data/freezes/20190412/MEG_E/etc/id.tsv"
# One of Medication_Biobank_Folder, Medication_GWAS_Group, Medication_Pegasus_Group, or ICS_or_ICS_LABA
medication_group:       "Medication_Biobank_Folder"
create_intermediates:   TRUE
intermediate_files_dir: "data/06-30-2020/IntermediateFiles/"
log_params:
  path:         "log_files/"
  file_ending:  ".log"
  level:        "DEBUG"
ACTH_params:
  skip_ACTH:              TRUE
  strict:                 FALSE
  create_cortisol_group:  TRUE
BMI_params:
  # Underweight = [0                  <= x < Underweight_Normal]
  # Normal      = [Underweight_Normal <= x < Normal_Overweight]
  # Overweight  = [Normal_Overweight  <= x < Overweight_Obese]
  # Obese       = [Overweight_Obese   <= x]
  Underweight_Normal: 18.5
  Normal_Overweight:  25
  Overweight_Obese:   30
