# File params
data_dir:               "data/06-30-2020/"
biobank_file_name:      "data/06-30-2020/BiobankPortal_mns43_2020-06-30-123319.csv"
output_file_header:     "data/06-30-2020/RPDR_cleaned_data_"
rpdr_file_header:       "data/06-30-2020/mns43_063020114847776198_"
rpdr_file_ending:       ".txt"
general_file_ending:    ".csv"
summary_stats_dir:      "data/06-30-2020/Summary_Stats/"
# One of Medication_Biobank_Folder, Medication_GWAS_Group, or Medication_Pegasus_Group
medication_group:       "Medication_Biobank_Folder"
create_intermediates:   TRUE
intermediate_files_dir: "data/IntermediateFiles/"
log_params:
  path:         "log_files/"
  file_ending:  ".log"
  level:        "DEBUG"
ACTH_params:
  skip_ACTH:              TRUE
  strict:                 FALSE
  create_cortisol_group:  TRUE
