# File params
data_dir:               "data/"
biobank_file_name:      "data/BiobankPortal_mns43_2020-02-12-124610.csv"
output_file_header:     "data/RPDR_cleaned_data_"
rpdr_file_header:       "data/mns43_100719120614239897_"
rpdr_file_ending:       ".txt"
general_file_ending:    ".csv"
create_intermediates:   TRUE
intermediate_files_dir: "data/IntermediateFiles/"
log_params:
  path:         "log_files/"
  file_ending:  ".log"
  level:        "DEBUG"
ACTH_params:
  skip_ACTH:              TRUE
  strict:                 FALSE
  create_cortisol_group:  TRUE
