# File params
data_dir: "data/"
rpdr_file_header: "data/mns43_100719120614239897_"
rpdr_file_ending: ".txt"
general_file_ending: ".csv"
biobank_file_name: "data/BiobankPortal_mns43_2019-09-18-150014.csv"
output_file_header: "data/RPDR_cleaned_data_"
select_files_dir: "data_dir/test/"
create_intermediates: TRUE
log_params:
  path: "log_files/"
  file_ending: ".log"
  level: "DEBUG"
ACTH_params:
  skip_ACTH: TRUE
  strict: FALSE
  create_cortisol_group: TRUE